### ISSUE TITLE
Validation failed: Element 'frames' is missing

### ISSUE THREAD

**Issue by ignatenkobrain** [abrt/abrt#819] opened 2014-05-31 21:36 UTC
```
--- Running report_uReport ---
Server responded with an error: 'Validation failed: Element 'frames' is missing'
reporter-ureport failed with exit code 1
('report_uReport' exited with 1)
```

abrt-2.2.1-4.fc21.x86_64

**Comment by xsuchy** [comment] 2017-05-11 11:30
I believe this is duplicate of https://github.com/abrt/abrt/issues/822

**Closed by xsuchy** 2017-05-11 11:30 UTC
