### ISSUE TITLE
Implement deduplication logic for clustering and merging of existing reports

### ISSUE THREAD

**Issue by mozeq** [abrt/abrt#429] opened 2013-02-04 12:27 UTC
Opened '20120402T14:12:28' by jmoskovc as https://fedorahosted.org/abrt/ticket/509

**Comment by xsuchy** [comment] 2020-06-09 14:11
Closing as dupe of https://github.com/abrt/abrt/issues/428

**Closed as completed by xsuchy** 2020-06-09 14:11 UTC
Labels: enhancement
